### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by YangPanHZAU** [Luo-Yihong/YOSO#1]
Thank you for the meaningful work. Have you considered open-sourcing the training code?

**Comment by Luo-Yihong** [comment]
Thanks for your attention to our work! We have considered open-sourcing, but we are currently busy with other projects. Optimistically, we estimate that we will complete the cleanup and reorganization of the training code and release it in May.

**Comment by Feynman1999** [comment]
> Thanks for your attention to our work! We have considered open-sourcing, but we are currently busy with other projects. Optimistically, we estimate that we will complete the cleanup and reorganization of the training code and release it in May.

Can we see your training code in May? I'm really looking forward to it!

**Comment by Luo-Yihong** [comment]
> > Thanks for your attention to our work! We have considered open-sourcing, but we are currently busy with other projects. Optimistically, we estimate that we will complete the cleanup and reorganization of the training code and release it in May.
> 
> Can we see your training code in May? I'm really looking forward to it!

The training script is released.
