### ISSUE TITLE
question about Adapt-stage-I in paper

### ISSUE THREAD

**Issue by Feynman1999** [Luo-Yihong/YOSO#5]
你好，作者，为了方便我直接用中文描述问题了～

我理解这里需要finetune网络 这里是怎么推导这个v_phi的？请指教，感谢🙏
<img width="1216" alt="image" src="https://github.com/Luo-Yihong/YOSO/assets/25549636/bcfc3871-860b-489e-b45e-ab5266b7dc19">

**Comment by Luo-Yihong** [comment]
谢谢你对我们工作的关注，这个是来自于《Progressive Distillation for Fast Sampling of Diffusion Models》的v-prediction，原始形式是：
![image](https://github.com/Luo-Yihong/YOSO/assets/65936780/337129f7-48c6-488c-9d77-db2364d910ff)
这里是把epsilon和x都换成了教师模型的预测结果了 希望能帮到你理解

**Comment by Feynman1999** [comment]
> 谢谢你对我们工作的关注，这个是来自于《Progressive Distillation for Fast Sampling of Diffusion Models》的v-prediction，原始形式是： ![image](https://private-user-images.githubusercontent.com/65936780/330868651-337129f7-48c6-488c-9d77-db2364d910ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjU5MTIsIm5iZiI6MTcxNTgyNTYxMiwicGF0aCI6Ii82NTkzNjc4MC8zMzA4Njg2NTEtMzM3MTI5ZjctNDhjNi00ODhjLTlkNzctZGIyMzY0ZDkxMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYzk1NGYyNjllMTZlMjkzNWZlZjMwMzAwMDM1NjY0NTJmMDE3NDUyNTJlMDk5MzE4YjYzODNmMzRlOTIxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wk2y7D57lVH6U1iKkEIa8rgkoj4D7lCjmCMQ9HfvaTE) 这里是把epsilon和x都换成了教师模型的预测结果了 希望能帮到你理解

嗯嗯，我根据v-prediction论文中的公式，成功推导了你们论文中的式子。
按照我的理解，adapt-stage1和2是不是一起进行的（训练1k iter)，还是说分开进行的？另外adapt时，如何采样时间t的？每个时间步的权重lambda_t如何设置？ 感谢指导🙏

**Comment by Luo-Yihong** [comment]
> > 谢谢你对我们工作的关注，这个是来自于《Progressive Distillation for Fast Sampling of Diffusion Models》的v-prediction，原始形式是： ![image](https://private-user-images.githubusercontent.com/65936780/330868651-337129f7-48c6-488c-9d77-db2364d910ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjU5MTIsIm5iZiI6MTcxNTgyNTYxMiwicGF0aCI6Ii82NTkzNjc4MC8zMzA4Njg2NTEtMzM3MTI5ZjctNDhjNi00ODhjLTlkNzctZGIyMzY0ZDkxMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYzk1NGYyNjllMTZlMjkzNWZlZjMwMzAwMDM1NjY0NTJmMDE3NDUyNTJlMDk5MzE4YjYzODNmMzRlOTIxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wk2y7D57lVH6U1iKkEIa8rgkoj4D7lCjmCMQ9HfvaTE) 这里是把epsilon和x都换成了教师模型的预测结果了 希望能帮到你理解
> 
> 嗯嗯，我根据v-prediction论文中的公式，成功推导了你们论文中的式子。 按照我的理解，adapt-stage1和2是不是一起进行的（训练1k iter)，还是说分开进行的？另外adapt时，如何采样时间t的？每个时间步的权重lambda_t如何设置？ 感谢指导🙏

我们各进行了500iters，如果你喜欢的话多跑一些迭代也是没问题的。

时间t是均匀采样，lambda_t=1

**Comment by Feynman1999** [comment]
> > > 谢谢你对我们工作的关注，这个是来自于《Progressive Distillation for Fast Sampling of Diffusion Models》的v-prediction，原始形式是： ![image](https://private-user-images.githubusercontent.com/65936780/330868651-337129f7-48c6-488c-9d77-db2364d910ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjU5MTIsIm5iZiI6MTcxNTgyNTYxMiwicGF0aCI6Ii82NTkzNjc4MC8zMzA4Njg2NTEtMzM3MTI5ZjctNDhjNi00ODhjLTlkNzctZGIyMzY0ZDkxMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYzk1NGYyNjllMTZlMjkzNWZlZjMwMzAwMDM1NjY0NTJmMDE3NDUyNTJlMDk5MzE4YjYzODNmMzRlOTIxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wk2y7D57lVH6U1iKkEIa8rgkoj4D7lCjmCMQ9HfvaTE) 这里是把epsilon和x都换成了教师模型的预测结果了 希望能帮到你理解
> > 
> > 
> > 嗯嗯，我根据v-prediction论文中的公式，成功推导了你们论文中的式子。 按照我的理解，adapt-stage1和2是不是一起进行的（训练1k iter)，还是说分开进行的？另外adapt时，如何采样时间t的？每个时间步的权重lambda_t如何设置？ 感谢指导🙏
> 
> 我们各进行了500iters，如果你喜欢的话多跑一些迭代也是没问题的。
> 
> 时间t是均匀采样，lambda_t=1

好的，你看我总结的这样的训练流程对吗：
0. 数据集均使用 JourneyDB
1. 500 iter , finetune网络到v-prediction
2. 500 iter,  zero SNR 调整 (这里是v_theta调整，v_phi依然用之前的scheduler? v_phi是per-trained model with ϵ-prediction)
3. L2 loss + adv loss + percerp loss + consistency loss       （这里时间t也是均匀采样吗？）

另外，期待训练代码的开源～ 🎉

**Comment by Luo-Yihong** [comment]
> > > > 谢谢你对我们工作的关注，这个是来自于《Progressive Distillation for Fast Sampling of Diffusion Models》的v-prediction，原始形式是： ![image](https://private-user-images.githubusercontent.com/65936780/330868651-337129f7-48c6-488c-9d77-db2364d910ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjU5MTIsIm5iZiI6MTcxNTgyNTYxMiwicGF0aCI6Ii82NTkzNjc4MC8zMzA4Njg2NTEtMzM3MTI5ZjctNDhjNi00ODhjLTlkNzctZGIyMzY0ZDkxMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyMTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYzk1NGYyNjllMTZlMjkzNWZlZjMwMzAwMDM1NjY0NTJmMDE3NDUyNTJlMDk5MzE4YjYzODNmMzRlOTIxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wk2y7D57lVH6U1iKkEIa8rgkoj4D7lCjmCMQ9HfvaTE) 这里是把epsilon和x都换成了教师模型的预测结果了 希望能帮到你理解
> > > 
> > > 
> > > 嗯嗯，我根据v-prediction论文中的公式，成功推导了你们论文中的式子。 按照我的理解，adapt-stage1和2是不是一起进行的（训练1k iter)，还是说分开进行的？另外adapt时，如何采样时间t的？每个时间步的权重lambda_t如何设置？ 感谢指导🙏
> > 
> > 
> > 我们各进行了500iters，如果你喜欢的话多跑一些迭代也是没问题的。
> > 时间t是均匀采样，lambda_t=1
> 
> 好的，你看我总结的这样的训练流程对吗： 0. 数据集均使用 JourneyDB
> 
> 1. 500 iter , finetune网络到v-prediction
> 2. 500 iter,  zero SNR 调整 (这里是v_theta调整，v_phi依然用之前的scheduler? v_phi是per-trained model with ϵ-prediction)
> 3. L2 loss + adv loss + percerp loss + consistency loss       （这里时间t也是均匀采样吗？）
> 
> 另外，期待训练代码的开源～ 🎉

对的，流程基本上是这样

训练代码这个月内会发布，敬请期待！

**Comment by Luo-Yihong** [comment]
训练代码开源了，我先把这个issue关掉，有进一步问题欢迎随时再打开

**Comment by Feynman1999** [comment]
还有几个疑问，您有空时指点下～
1. 判别器是不是也要输入文本信息?  
2. 判别器为什么要输入时间步的信息
3. 推理的时候，timestep如何设置，设置不同的值有显著区别吗
