### ISSUE TITLE
About coop_latents and fake_latents

### ISSUE THREAD

**Issue by Hzj199** [Luo-Yihong/YOSO#6]
Thanks for sharing your code and making it openly available. It's been very helpful.

I have a query about `coop_latents ` and  `fake_latents`. Why can `coop_latents` be used as input for `unet_gan`, while `fake_latents` need to be processed through the calculation `fake_latents = c_skip_start * noisy_latents + c_out_start * fake_latents` before being used as input for `unet_gan`?

**Comment by Luo-Yihong** [comment]
This is indeed a bug in the code; I omitted this while organizing the code. 

Thanks for pointing it out! I will fix it soon.
