### ISSUE TITLE
请教一下 Self-Cooperative和consistency loss

### ISSUE THREAD

**Issue by Hzj199** [Luo-Yihong/YOSO#7]
您好，我仔细读了代码和论文，有两个地方不太理解，向您请教一下：
1. https://github.com/Luo-Yihong/YOSO/blob/b962ff94adc9d8dbd98a0050d97fd6d466d0808e/train_yoso_lora.py#L905C1-L943C51 这部分代码就是Self-Cooperative吗？用 prev_t_d  的生成结果当做Ground Truth （对应论文中的Note that we only replace data distribution as p(t−1)θ(x) in theadversarial divergence for smoothing the learning objective）
2. https://github.com/Luo-Yihong/YOSO/blob/b962ff94adc9d8dbd98a0050d97fd6d466d0808e/train_yoso_lora.py#L975-L987 为什么prev_noisy_latents 为什么不是像[lcm](https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/train_lcm_distill_lora_sd_wds.py)中通过teacher_unet计算得到，而是直接加噪获得

**Comment by Luo-Yihong** [comment]
1. 对的。
2. 这里是为了和文章中的用低噪声作ground truth训练相吻合。从另一个角度说，YOSO的目标是设计一种新型的生成模型而不是单纯的蒸馏，所以这里没采用teacher_unet；而LCM是执行的一致性蒸馏，支持从头训练的一致性训练也是直接加噪。
3. 存在设置teacher_unet = unet，然后解ODE方程获得pre_noisy_latents进行训练的方案，并且可能获得更好的性能。我们未来可能会尝试训练这个版本的YOSO。
